# Generated by Django 4.2.16 on 2026-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqevent',
            name='timestamp_ms',
            field=models.IntegerField(default=0, help_text='Simulated time offset in milliseconds from session start'),
        ),
        migrations.AlterField(
            model_name='arqsession',
            name='loss_probability',
            field=models.FloatField(default=0.2, help_text='Simulated packet loss probability (0.0 – 1.0)'),
        ),
    ]
