# Generated by Django 4.2.16 on 2026-06-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__student_3ebc33_idx',
            old_name='attendance_student_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__lecture_1127b5_idx',
            old_name='attendance_lecturer_idx',
        ),
    ]
