# Generated by Django 4.2.16 on 2026-06-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_lecture_96080f_idx',
            old_name='reviews_lecturer_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_student_54799b_idx',
            old_name='reviews_student_idx',
        ),
    ]
